### PR TITLE
Jiaxx review

### PR DESCRIPTION
**Pull request by Laohusong**
This is our committed branch. Take care before merging because of the version problem.

### CODE REVIEW

**Comment by jeromelecoq** [comment]
Many thanks for your contribution!
We will go over this in the next weeks. Note that some team members are out of office until mid-June so we will go in bigger depth then.

**Comment by rcpeene** [comment]
This all looks very good! Thank you for your changes.

The only question I have is about the changes pushed for the `download_nwb.ipynb`. It looks like the first cell has error output from a keyboard interrupt. Was that a mistake?

**Comment by Laohusong** [comment]
I have fixed the errors. They are just keyboard interrupts😂, sorry. (Ignore the last two commits)

**Comment by rcpeene** [comment]
Was there an error in your merge? It looks like a lot of the changes are actually undoing changes I have made to our main branch in the past few weeks? For instance, the diffs of build.yml, test.yml, contributors.csv, etc.

It could be pretty harmful to accidentally undo a lot of these changes, perhaps you need to try to redo the merge or pull our main into your local branch?

**Comment by Laohusong** [comment]
I am sorry for the confusing merges and undos. The github automatically merged the branch before pushing. And I reverted it. So the last two commits made no changes in total.

**Comment by Laohusong** [comment]
> perhaps you need to try to redo the merge or pull our main into your local branch?

But I agree with it. The commits are based on an older version, so it may be necessary to pull the main and test again. I will do it later.

**Comment by rcpeene** [comment]
Alright thanks!

**Comment by Laohusong** [comment]
I tested the commits in a new PR, which is based on the new main branch. This one will be closed.

**Pull request closed without merging**
